# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healthapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for healthapp

  target 'healthappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'healthappUITests' do
    # Pods for testing
  end
pod 'Firebase/Auth'
pod 'Firebase/Crashlytics'
    pod 'JJFloatingActionButton'
pod 'Firebase/Database'
pod 'AARatingBar'

pod 'Firebase/Analytics'
end
